version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: tts_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: tts_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      # Mount source code for live reload with nodemon
      - ./src:/usr/src/app/src
    env_file:
      - ./.env
    # Use dev script to enable nodemon
    command: npm run dev
