FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY ecosystem.prod.config.cjs .
RUN npm install -g pm2
EXPOSE 3001
CMD ["pm2-runtime", "start", "ecosystem.prod.config.cjs"]
